mongo:
  image: "mongo:3"
elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
  volumes:
    - /opt/graylog/data/elasticsearch:/usr/share/elasticsearch/data
graylog:
  image: graylog2/server:2.0.0-1
  volumes:
    - /opt/graylog/data/journal:/usr/share/graylog/data/journal
    - /opt/graylog/config:/usr/share/graylog/data/config
  environment:
    GRAYLOG_PASSWORD_SECRET: tiki@1234
    GRAYLOG_ROOT_PASSWORD_SHA2: 4ed84f76c1192d353592374aead0b5fdaabe6886f8a09af9bbb1d7d534438863
    GRAYLOG_REST_TRANSPORT_URI: http://52.77.222.248:12900
  links:
    - mongo:mongo
    - elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
    - "12201/udp:12201/udp"
    - "1514/udp:1514/udp"
